Implement boot with AMD SKINIT
TrenchBoot/linux pull request #130
Opened 2024-10-28 23:18 UTC by SergiiDmytruk

2024-10-29 19:49 UTC, krystian-hebel requested changes

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/boot/compressed/sl_main.c
> +	if ((sl_cpu_type & SL_CPU_INTEL) &&
This check isn't necessary, `sl_txt_validate_event_log_buffer()` is called only on Intel anyway.

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/boot/compressed/sl_main.c
>  	 * the MLE image.
While technically this is more or less the same test as done on AMD, it doesn't sound like that in this comment. Perhaps adding an information of what MLE consists of would help.

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/boot/compressed/sl_main.c
> +				    kernel_end))
Is this something we should be worried about? If the kernel code would overlap with bootparams, it would mean that GRUB did something it shouldn't, and we couldn't depend on `bp->hdr.code32_start` being valid anyway.

I think checking for overlap between bootparams and event log would make more sense.

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/boot/compressed/sl_main.c
> +	 * through the Secure Launch entry point and is the CPU is in a suitable
```suggestion
	 * through the Secure Launch entry point and the CPU is in a suitable
```

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/boot/compressed/sl_main.c
>  	bp->hdr.loadflags |= SLAUNCH_FLAG;
This should be moved as well, the comment mentions it.

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/boot/compressed/sl_stub.S
> +	 * the offset everywhere.
We should make SKL return it as TXT does. It started as a quick hack before common entry point to Xen was considered. We have to obtain MBI for Intel anyway, and having a consistent state on entry point is more important. I already assumed this would be the case [when rebasing Xen](https://github.com/TrenchBoot/xen/blob/aem-staging-14-10-24-rebase/xen/arch/x86/boot/head.S#L376) for upcoming AEM phase and I was sure I did the same for SKL but I must've forgot to push it, I'll have to check on PC later.

As i already mentioned somewhere, on Intel it isn't possible to do a `call`/`pop` trick if `%ss` isn't valid, which is yet another reason to make the state on entry compatible between vendors.

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/kernel/slmodule.c
>  	params = (struct txt_os_mle_data *)txt_os_mle_data_start(txt_heap);
This already accesses TXT heap, so the mapping can't be moved from above.

2024-10-29 19:49 UTC, krystian-hebel commented on arch/x86/kernel/traps.c
> +	/* If SKINIT was done on the BSP, this is the spot to enable GIF */
According to `Software Requirements for Secure MP initialization` in 24593 AMD APM Vol.2, SKINIT can be invoked on BSP only, the way this comment is written may suggest otherwise. Maybe something like:

```suggestion
	/* On the BSP, this is the spot to enable GIF if SKINIT was done  */
```

2024-10-29 19:49 UTC, krystian-hebel commented on include/linux/slaunch.h
> + * the TCG documentation. For TXT this is setup as the container header. On AMD
```suggestion
 * the TCG documentation. For TXT this is set up as the container header. On AMD
```

2024-10-29 23:33 UTC, SergiiDmytruk commented on arch/x86/boot/compressed/sl_main.c
> +	if ((sl_cpu_type & SL_CPU_INTEL) &&
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-e505e4ef3afb000972d3fd8c5ae02ff53e90f744fbaf4c22b5872d85e2536474R338

2024-10-29 23:33 UTC, SergiiDmytruk commented on arch/x86/boot/compressed/sl_main.c
>  	 * the MLE image.
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-e505e4ef3afb000972d3fd8c5ae02ff53e90f744fbaf4c22b5872d85e2536474R328

2024-10-29 23:33 UTC, SergiiDmytruk commented on arch/x86/boot/compressed/sl_main.c
> +				    kernel_end))
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-e505e4ef3afb000972d3fd8c5ae02ff53e90f744fbaf4c22b5872d85e2536474R355-R362

2024-10-29 23:33 UTC, SergiiDmytruk commented on arch/x86/boot/compressed/sl_main.c
> +	 * through the Secure Launch entry point and is the CPU is in a suitable
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-e505e4ef3afb000972d3fd8c5ae02ff53e90f744fbaf4c22b5872d85e2536474R641

2024-10-29 23:33 UTC, SergiiDmytruk commented on arch/x86/boot/compressed/sl_main.c
>  	bp->hdr.loadflags |= SLAUNCH_FLAG;
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-e505e4ef3afb000972d3fd8c5ae02ff53e90f744fbaf4c22b5872d85e2536474R657-R674

2024-10-29 23:34 UTC, SergiiDmytruk commented on arch/x86/boot/compressed/sl_stub.S
> +	 * the offset everywhere.
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-4a7531926d6866ad0154ebd708509b9fa54d5bbcbd0a9981880ef4d2fe993311

Updated SKL locally after doing the change, OSFV tests still pass.

2024-10-29 23:34 UTC, SergiiDmytruk commented on arch/x86/kernel/slmodule.c
>  	params = (struct txt_os_mle_data *)txt_os_mle_data_start(txt_heap);
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-6027baf7ab71879448c4e249e4b1f3fa2689a6c1d7113a564b1605ae9850a995

2024-10-29 23:34 UTC, SergiiDmytruk commented on arch/x86/kernel/traps.c
> +	/* If SKINIT was done on the BSP, this is the spot to enable GIF */
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-51ce909c2f65ed9cc668bc36cc3c18528541d8a10e84287874cd37a5918abae5

2024-10-29 23:34 UTC, SergiiDmytruk commented on include/linux/slaunch.h
> + * the TCG documentation. For TXT this is setup as the container header. On AMD
https://github.com/TrenchBoot/linux/compare/bfc6b41c8d4bdebc6eab7a762f03f0010ab06f0e..1f29b6db37352ae156ab2e1a2cd62e7e050659cf#diff-1ba7aea591efe255c8bb9f65ce792165bbc5fc4b41bc4f26cfb4bae439a8c780

2024-10-30 11:12 UTC, krystian-hebel commented on arch/x86/boot/compressed/sl_main.c
> +				    kernel_end))
There is also mention of this in https://github.com/TrenchBoot/linux/pull/130/files#diff-e505e4ef3afb000972d3fd8c5ae02ff53e90f744fbaf4c22b5872d85e2536474R664, it must also be changed.

2024-10-30 12:02 UTC, SergiiDmytruk commented on arch/x86/boot/compressed/sl_main.c
> +				    kernel_end))
https://github.com/TrenchBoot/linux/compare/1f29b6db37352ae156ab2e1a2cd62e7e050659cf..b3a71004fec51568b9715ac00312e2bacf2e073f

2024-11-07 20:53 UTC, krystian-hebel approved these changes

2024-11-07 21:11 UTC, merged